internship_application/config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'

  devise_for :users,skip:[:registration]
  root "votes#new"
  
  get 'votes/new'

  get 'cats/index'

  resources :votes
  resources :cats
  resources :reports,only:[:index]

end

internship_application/app/models/cat.rb
class Cat < ActiveRecord::Base
    validates_presence_of :url
    has_many :votes
end

internship_application/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

internship_application/app/models/vote.rb
class Vote < ActiveRecord::Base
    validates_presence_of :cat_id,:ip,:vote_type_id
    #validates :vote_name,inclusion: { in: ["Amazing! So Beautiful!","ZOMG! So Cute!"] }
    belongs_to :cat
    belongs_to :vote_type
    
    def self.to_csv 
        CSV.generate do |csv|
           csv << [:url,:ip,:vote]
            all_votes.each do |vote|
                csv << [vote.url,vote.ip,vote.name]
            end
        end
    end
    
    def self.all_votes
       joins(:cat,:vote_type)
       .select(:url,:ip,:name)
        
    end
    
    def self.ranked_by(vote_type_id)
        joins(:cat,:vote_type)
        .group("Cats.url","vote_types.name")
        .where("vote_type_id = ?",vote_type_id)
        .order("count_all desc")
        .count
    end
end

internship_application/app/models/vote_type.rb
class VoteType < ActiveRecord::Base
    has_many :votes
end

internship_application/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

internship_application/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end
  def new
    @cat = Cat.new
  end
  def show
    @cat = Cat.find params[:id]
  end
  def edit
    @cat = Cat.find params[:id]
  end
  
  def create
    @cat  = Cat.new cat_params
    if @cat.save
      flash[:success] = "（ΦωΦ）Cat created corretcly meow （ΦωΦ）!!!"
      redirect_to cats_path
    else
      render 'new'
    end
  end

  def update
    @cat = Cat.find params[:id]
    if @cat.update cat_params
      flash[:success] = "（ΦωΦ） update successfully （ΦωΦ）"
      redirect_to @cat
    else
      render 'edit'
    end
  end
  
  def destroy
    Cat.destroy(params[:id])
    flash[:info] = "(ↀДↀ)）Cat deleted (ↀДↀ)"    
    redirect_to cats_path
  end

  private
  def cat_params
    params.require(:cat).permit(:url)
  end
end

internship_application/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    vote_type = (params[:order_by].present?) ? VoteType.find_by_name(params[:order_by]) : VoteType.first
  
    @vote_types = VoteType.all
    @top_cats = Vote.ranked_by vote_type.id
  end
end

internship_application/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :verify_vote_types_count
  
  def index
    @votes = Vote.all_votes
    respond_to do |format|
      format.csv { send_data @votes.to_csv }
    end
  
  end
  
  def new
    @votes_types =  VoteType.all
    @cats = Cat.offset(next_page).limit(2)
  end
  
  def create
    @vote = Vote.new(cat_id: params[:cat_id],vote_type_id: params[:vote_type_id], ip: request.remote_ip)
    if @vote.save
      flash[:success] = 'Thanks for vote!!!!!'
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  private
  def next_page()
    if cookies[:next_cats]
     cookies[:next_cats]  =cookies[:next_cats].to_i + 2
      cookies[:next_cats] = (cookies[:next_cats].to_i > Cat.all.count) ? 0 : cookies[:next_cats]
    else
      cookies[:next_cats] = 0
    end
  end
  def verify_vote_types_count
    render text:"please run rake db:seed before run the application" if VoteType.count < 2
  end
end

internship_application/app/helpers/application_helper.rb
module ApplicationHelper
end

internship_application/app/helpers/cats_helper.rb
module CatsHelper
end

internship_application/app/helpers/reports_helper.rb
module ReportsHelper
end

internship_application/app/helpers/votes_helper.rb
module VotesHelper
    
    def vote_name(index)
        names = ["Amazing! So Beautiful!","ZOMG! So Cute!"]
        return names[index]
    end
end

internship_application/app/views/cats/_form.html.erb
<div class="row">
  <%= form_for(@cat,html:{ class:"col-md-6"}) do |f| %>
      <div class="form-group">
        <%= f.label :url,"URL"%>
        <%= f.text_field :url,class:"form-control" %>
      </div>
      <%= f.submit nil,class:"btn btn-success" %>
   
  <% end %>

</div>

internship_application/app/views/cats/_shared.html.erb
 <div class="shared">
    <%= link_to 'See Cats', cats_path %> || 
    <%= link_to 'New Cat', new_cat_path %>

 </div>

internship_application/app/views/cats/edit.html.erb
<div class="image_cat">
  <%= image_tag(@cat.url,class:"img-rounded md-thumbnail")%>  
</div>

<%= render "form" %>
<%= render "shared" %>

internship_application/app/views/cats/index.html.erb
<h1><%= link_to("Add new Cat",new_cat_path)%></h1>
<p>Click cat for show it</p>

<table class="table table-striped">
    <thead>
        <th>
            CAT
        </th>
        <th>
           URL 
        </th>

        <th>
            Edit
        </th>
        <th>
            Delete
        </th>
    </thead>
<% @cats.each do |cat| %>
    <tr>
        <td>
            <%= link_to(image_tag(cat.url,width:"150",height:"150",class:"grow-image"),cat_path(cat))%>
        </td>
        <td>
           <%= link_to(cat.url,cat.url,target:"_blank") %>
        </td>
        <td>
            <%= link_to("Edit",edit_cat_path(cat)) %>
        </td>
        <td>
            <%= link_to("Delete",cat_path(cat),method: :delete,data:{confirm:"Are u sure want delete this beautiful cat, well i think so"})%>
        </td>
    </tr>
<% end %>
</table>

internship_application/app/views/cats/new.html.erb
<h1>Creating a cat</h1>

<%= render "form" %>


<%= render "shared"%>

internship_application/app/views/cats/show.html.erb
<div class="row">
    <div class="media">
      <div class="media-left">
          <%= image_tag(@cat.url,class:" md-thumbnail")%>
      </div>
      <div class="media-body">
        <h4 class="media-heading"> <%= link_to(@cat.url,@cat.url,target:"_blank") %></h4>
         Description here
      </div>
    </div>    

    
</div>

<%= render "shared"%>

internship_application/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InternshipApplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <%= link_to("ZOMG! CAT HEALTH!",root_path,class:"navbar-brand") %>
          </div>
          <div>
              <ul class="nav navbar-nav">
                <li class="active"><%= link_to("Administrator",user_session_path) unless user_signed_in? %></li>
                <% if user_signed_in? %>
                <li><%= link_to "Cats",cats_path%>  </li>
                <li><%= link_to "Reports Cats",reports_path%> </li>
                <li><%= link_to "Sign out",destroy_user_session_path,method: :delete %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>
<%# debug flash%>
<% flash.each do |type,message|%>
<div class="alert alert-<%= type %>">
    <%= message %>
</div>
<% end %>
<%= yield %>
</div>
</body>
</html>

internship_application/app/views/reports/index.html.erb
<div class="page-header">
  <h1>Reports Cat <small><%= "No person has voted yet" if @top_cats.empty? %> </small></h1>
</div>
<h4>order by </h4>
<% @vote_types.each do |vote_type| %>

    <%= link_to(vote_type.name,reports_path(order_by: vote_type.name) )%>  -

<% end %>
<div>
    <hr/>
     <%= link_to("Export to csv", votes_path(format:"csv") )%>
</div>

 
 
<div class="row">
  <% @top_cats.each_with_index do |top_cat,i| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
           <%= image_tag(top_cat[0][0])%>
          <div class="caption" style="text-align: center;">
            <button class="btn btn-primary" type="button">
              <%= top_cat[0][1] %> <span class="badge"><%= top_cat[1] %></span>
            </button>
        
          </div>
        </div>
      </div>
 
    <% end %>
</div>

internship_application/app/views/votes/new.html.erb
<div clsas="row"> 
    
    <% @cats.each_with_index do |cat,i| %>
    <div class="col-md-4 col-md-offset-1">
    
        <%= form_for(cat.votes.build) do |f| %>
        <%= hidden_field_tag :cat_id,cat.id %>
        <div class="thumbnail">
            <%= image_tag(cat.url,class:"img-ronded img-thumbnail img-responsive") %>
            <div class="caption">

                <%= hidden_field_tag :vote_type_id,@votes_types[i].id %>
                <%= f.submit @votes_types[i].name,class:"btn btn-primary" %>
               
            </div>
        </div>
        <% end %>
    </div>
    <% end %>


</div>